travail autour du spinner
pebble-solutions/app-mate pull request #27
Opened 2024-03-13 16:27 UTC by deathtroll22

Les deux problèmes relatifs au spinner sont traités.

- Le spinner est un composant qui apparaît lorsqu'on édite ou supprime une activité, et également lors des options de mandatory, d'ajout de variable à l'activité (addVariableToActivity) et de suppression de variable de l'activité (removeVariableFromActivity). 
- J'ai dû modifier deux méthodes dans le contexte de l'activité (ActivityContext) pour les rendre asynchrones et permettre ainsi l'affichage du spinner.

J'ai également placé la partie réglages d'activité dans une modale, car c'était inesthétique autrement.

2024-03-18 10:02 UTC, Guillaume35 requested changes

2024-03-18 10:02 UTC, Guillaume35 commented on app/(tabs)/activities/[id].tsx
> +        await removeActivity(activity._id);
Fichier shared/context/ActivityContext.tsx 
La signature de la fonction removeActivity à la ligne 9 est erronée. Elle doit retourner une promesse. Modifier pour :

```TypeScript
removeActivity: (id: string) => Promise<void>
```

2024-03-18 10:02 UTC, Guillaume35 commented on app/(tabs)/activities/[id].tsx
> +            console.error("Erreur lors de la mise à jour de l'activité:", error);
Les erreurs doivent apparaître à l'écran de l'utilisateur via la méthode `Alert.alert()`

Par ailleurs, si une erreur survient, les paramètres ne doivent pas être masqué (puisqu'il y a une erreur et que les données sont potentiellement non enregistrées).

`setSettingsVisible(false)` de la close _finally_ doit être remonté sous le `await editActivity()` à l'intérieur du _try_

Le déroulé logique doit être le suivant :

1. _try_ : On tente de modifier l'activité puis de masquer les settings si aucune erreur ne se déroule
2. _catch_ : Si une erreur intervient, on l'affiche à l'utilisateur
3. _finally_ : Dans tous les cas, le loader est masqué à la fin de l'opération (avec ou sans erreur)

2024-03-18 10:02 UTC, Guillaume35 commented on app/(tabs)/activities/[id].tsx
> +                <Modal
Revoir la structure du code :

1. Ce composant modal avec l'ensemble des styles associés doit être mis à l'intérieur d'un composant générique (Balise` <Modal>, <View modalBackground>, <View modalContainer>`) (/components/modal.tsx). Ce composant surcharge le composant de base de ReactNative afin de pouvoir être utilisé dans d'autres écrans avec le même design
2. Le compostant de formulaire de modification doit être intégré dans un composant dédiée (/components/activity/SettingsForm.tsx) puis appelé au niveau de cet écran. Le composant SettingsForm peut prendre des paramètres tel que l'activité à modifier, si le bouton supprimer doit être actif ou non... le composant SettingsForm accepte les options suivantes : onValidate, onDelete qui permettent de déclencher les actions au niveau du screen.

2024-03-18 10:02 UTC, Guillaume35 commented on app/(tabs)/activities/[id].tsx
> +                                onPress={showConfirmDeleteDialog}
`showConfirmDeleteDialog` n'est pas le bon nom de fonction dans ce contexte. Cela devrait être `handleDeleteActivity` par exemple. La fonction doit à la fois générer l'affichage de la boite de dialogue de confirmation, mais aussi la suppression lorsque la boite de dialogue est confirmée.

2024-03-18 10:02 UTC, Guillaume35 commented on app/(tabs)/activities/[id].tsx
> +                                onPress={() => {
Créer une fonction de callback pour tout ça : `handleUpdateActivity` par exemple.

2024-03-18 10:02 UTC, Guillaume35 commented on app/(tabs)/activities/[id].tsx
> +                            onActionEnd={() => setIsLoading(false)}
Il n'y a pas besoin de créer deux attributs ici. Un seul suffit passant l'état du loader (`onLoaderChange` par exemple).

```TypeScript
onLoaderChange={(newVal) => setIsLoading(newVal)}
```

2024-03-18 10:02 UTC, Guillaume35 commented on app/(tabs)/activities/[id].tsx
> +                            onActionEnd={() => setIsLoading(false)}
Idem au commentaire précédent

2024-03-18 10:02 UTC, Guillaume35 commented on components/SpinnerLoader.tsx
Au niveau du nom du composant, je serai un peut plus explicite sur le mode d'affichage. Il s'agit d'un spinner qui couvre l'ensemble de l'écran.

_ScreenCoverLoader.tsx_

2024-03-18 10:02 UTC, Guillaume35 commented on components/SpinnerLoader.tsx
> +        backgroundColor: 'rgba(0, 0, 0, 0.5)',
Dans le fichier globalStyle, ajouter la variable color.alphaDark et la récupérer ici. Cette couleur pourra être réutilisé dans toutes les vues nécessitant la même chose, avec les même réglages.

`variables.color.alphaDark`

2024-03-18 10:02 UTC, Guillaume35 commented on components/VariableCard.tsx
> +    onActionEnd?: () => void;
Changer les deux attributs pour 

`onLoaderChange?: (newVal: boolean) => void`

2024-03-18 10:02 UTC, Guillaume35 commented on components/VariableCard.tsx
> +        if (onActionStart) onActionStart();
Modifier tout ça : créer une un state loaderStatus,

```TypeScript
[loaderStatus, setLoaderStatus] = useState(false)
```

observer la modification du status :

```TypeScript
useEffect(() => {
    if (typeof onLoaderChange !== "undefined") onLoaderChange(loaderStatus)
}, [loaderStatus])
```

créer deux fonction : loaderStart et loaderEnd

```TypeScript
const loaderStart = () => {
    setLoaderStatus(() => true)
}

const loaderEnd = () => {
   setLoaderStatus(() => false)
}
```

Appeler loaderStart() au début de chaque action et loaderEnd() à la fin.

2024-03-18 10:02 UTC, Guillaume35 commented on shared/contexts/ActivityContext.tsx
> +                return true; // Indique le succès de l'opération
Ces modifications sortent du champ de la fonctionnalité développées. Je ne vais pas détailler ici, mais tout cela sera revu.

2024-03-18 10:02 UTC, Guillaume35 commented on shared/globalStyles.ts
> +    modalBackground: {
modalBackground et modalContainer doivent être retirés de globalStyles et ajoutés dans un composant dédié.

2024-03-18 10:02 UTC, Guillaume35 commented on shared/globalStyles.ts
> +        backgroundColor: 'rgba(0, 0, 0, 0.5)',  // Fond semi-transparent
Utiliser la variable générique mentionné plus haut alphaDark.

2024-03-18 10:02 UTC, Guillaume35 commented on shared/globalStyles.ts
> +        backgroundColor: '#11212D',
Utiliser une variable générique.

2024-03-18 10:02 UTC, Guillaume35 commented on shared/globalStyles.ts
> +        borderRadius: 20,
Utiliser une variable générique borderRadius (déja existante)

2024-03-18 10:02 UTC, Guillaume35 commented on shared/globalStyles.ts
> +        padding: 20,
Utiliser une variable générique contentPadding (déjà existante)

2024-03-18 10:02 UTC, Guillaume35 commented on shared/globalStyles.ts
> +        shadowColor: '#000',
Utiliser des variables génériques pour les shadow.

2024-03-18 10:05 UTC, Guillaume35 commented
Les conflits doivent être résolut avant demande de fusion :

Step 1: Clone the repository or update your local repository with the latest changes.
`git pull origin unstable`

Step 2: Switch to the head branch of the pull request.
`git checkout ActivityIndicator`

Step 3: Merge the base branch into the head branch.
`git merge unstable`

Step 4: Fix the conflicts and commit the result.

Step 5: Push the changes.
`git push -u origin ActivityIndicator`

2024-03-20 18:47 UTC, deathtroll22 commented on app/(tabs)/activities/[id].tsx
> +                <Modal
on utilisai deja la l'affichage de composant dans le style modal systeme grace au activitylayout. j'ai donc fusionné les codes pour l'edition d'une activité avec celui de la creation en prenant en compe deux Modes dans les props qui gere un affichage conditionnel des elements. cela n'empeche pas quon aura peut etre besoin d'une vraie modale par la suite pour d'autres choses mais je prefere utiliser le mode existant (lors de la creation) qui est plus sympa. j'ai donc créé le composant activityModal.tsx qui gere deux cas d'utilisation

2024-03-21 09:48 UTC, deathtroll22 commented on components/SpinnerLoader.tsx
fichier renommé

2024-03-26 09:18 UTC, Guillaume35 approved these changes

2024-03-26 09:18 UTC, Guillaume35 commented on app/(tabs)/activities/[id].tsx
> +            {isSettingsVisible && (
La modal doit pouvoir être fermée.

2024-03-26 09:18 UTC, merged