Modify session
pebble-solutions/app-mate pull request #29
Opened 2024-03-18 08:32 UTC by marilehoux

modification composants textInput, booleanInput et date time input pour qu'ils soient compatibles avec Android
modification variablesResume pour rendre les sequences et les variables editables.

2024-03-18 13:17 UTC, Guillaume35 requested changes

2024-03-18 13:17 UTC, Guillaume35 commented on app/(tabs)/session/validate.tsx
> +            <Text style={globalStyles.textLight}>{currentSession.start.toLocaleDateString()}</Text>
Les deux éléments ci dessus devraient être en en-tête de toutes les étapes de validation et non uniquement sur le récap.

Éléments de solution : 

1. Créer un composant components/Session/SummaryHeader.tsx qui reprend les deux informations ci-dessus (label et date de début)
2. Ajouter ce composant en en-tête de la présente vue (au niveau de la ligne 135 environ).

2024-03-18 13:17 UTC, Guillaume35 commented on app/(tabs)/session/validate.tsx
> +            <StopWatch
Actions à réaliser :

- Ajouter un libellé au dessus "Durée totale de la session"
- Ajouter un attribut _size_ dans le composant StopWatch. Cet attribut size gère la taille du texte et accepte les valeures suivantes : _sm_, _md_ (actuelle, par défaut), _lg_, _xl_ . Si size n'est pas renseigné, alors c'est la valeur md qui est utilisé.

2024-03-18 13:17 UTC, Guillaume35 commented on app/(tabs)/session/validate.tsx
> +            <Title title={"Pointages"} style={[globalStyles.mb2Container, globalStyles.textLight]} />
Remplacer le titre "Pointage" par le titre "Séquences"

2024-03-18 13:17 UTC, Guillaume35 commented on app/(tabs)/session/validate.tsx
> +            <Title title={"Informations fournies"} style={[globalStyles.mb2Container, globalStyles.textLight]} />
Remplacer `globalStyles.mb2Container` par `globalStyles.my2Container` (créer le style si il n'existe pas).

2024-03-18 13:17 UTC, Guillaume35 commented on app/(tabs)/session/validate.tsx
> +            <View style={globalStyles.mt2Container}>
Ce composant semble servir uniquement à gérer la marge technique de android. Il faut trouver un autre moyen pour ne pas interférer avec le SafeAreaView qui gère la marge de iOs

2024-03-18 13:17 UTC, Guillaume35 commented on app/(tabs)/session/validate.tsx
> +    containerLocal: {
Les attributs ne semblent pas nécessaire.

Utiliser "body" de globalStyles à la place pour le même résultat.

2024-03-18 13:17 UTC, Guillaume35 commented on components/Form/DateTimeInput.tsx
Le mode de fonctionnement sous iOs est problématique :

Il faut cliquer une première fois sur la valeur active de la date à gauche pour ensuite cliquer sur la valeur à modifier à droite pour ensuite accéder au selecteur.

Il est nécessaire de modifier cela pour n'avoir à cliquer qu'une seule fois sur la date ou l'heure afin d'afficher le selecteur.

<img width="438" alt="Capture d’écran 2024-03-18 à 13 35 53" src="https://github.com/pebble-solutions/app-mate/assets/945411/dd32cd0a-8631-4855-9a77-4917218def18">

2024-03-18 13:17 UTC, Guillaume35 commented on components/Form/FormInput.tsx
> +import TextInputC from "./TextInputC";
Le fichier TextInput ne doit pas changer. Il doit bien se nommer TextInput.tsx

2024-03-18 13:17 UTC, Guillaume35 commented on components/Form/TextInputC.tsx
Le fichier TextInput.tsx ne doit pas être renommé

2024-03-18 13:17 UTC, Guillaume35 commented on components/Form/TextInputC.tsx
> -import { TextInput as ReactTextInput } from 'react-native';
Rétablir cette ligne

2024-03-18 13:17 UTC, Guillaume35 commented on components/Form/TextInputC.tsx
> +import { TextInput } from "react-native";
Supprimer cette ligne

2024-03-18 13:17 UTC, Guillaume35 commented on components/Form/TextInputC.tsx
> +const TextInputC = ({value, onChange, placeholder, multiline}: TextInputOptions) => {
Rétablir la version précédente.

2024-03-18 13:17 UTC, Guillaume35 commented on components/Form/TextInputC.tsx
> +        <TextInput
Rétablir la ligne précédente.

2024-03-18 13:17 UTC, Guillaume35 commented on components/Form/TextInputC.tsx
> +export default TextInputC;
Rétablir la ligne précédente.

2024-03-18 13:17 UTC, Guillaume35 commented on components/Onboarding/OnboardingController.tsx
> +import VariablesResume from "../Session/VariablesResume";
Ce fichier ne devrait pas être importé ici.

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/SequenceItem.tsx
> +    const [isEditable, setIsEditable] = React.useState(false);
Remplacer le nom de la variable par `[editMode, setEditMode]`

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/SequenceItem.tsx
> +    const [updatedItem0, setUpdatedItem0] = React.useState<Date>(item[0]);
remplacer le nom de la variable par `[updatedDateStart, setUpdatedDateStart]`

Créer la `[updatedDateEnd, setUpdatedDateEnd]`

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/SequenceItem.tsx
> +    , [updatedItem0])
Supprimer le useEffect qui génère une boucle sur updatedItem0

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/SequenceItem.tsx
> +                    <View style={localStyle.small}>
A la place de localStyle.small , utiliser les flex box pour créer deux colonnes : 

`style={localStyle.inputContainer}`

```
inputContainer: {
    flex:0.5
}
```

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/SequenceItem.tsx
> +    const handleChangeValue = (newVal: Date) => {
Modifier pour `handleChangeDateStart` et créer `handerChangeDateEnd`

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/SequenceItem.tsx
> +                            placeholder={item[0].toLocaleTimeString()}
Le placeholder doit être basé sur item[1]

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/SequenceItem.tsx
> +    small: {
Normalement non nécessaire.

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/SequenceList.tsx
> +import Title from "../Title";
L'import de Title n'est pas utile.

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/SequenceList.tsx
> +import { globalStyles } from "../../shared/globalStyles";
l'import de globalStyles n'est pas utile.

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/VariableItem.tsx
> +    const [isEditable, setIsEditable] = React.useState(false)
Remplacer par `[editMode, setEditMode]`

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/VariableItem.tsx
> +            str = value ? value.toString() : "Non-renseigné"
bien vu !!!!

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/VariableItem.tsx
> +    }, [variable.value])
Il y a un risque d'une boucle infinie puisque value met à jour la parent et le parent met à jour value. À contrôler si ce useEffect ne peut pas être transformé en une initialisation unique lors du montage du composant.

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/VariableItem.tsx
> +                        <ButtonPrevNext
Indentation : -1

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/VariableItem.tsx
> +import ButtonPrevNext from "../TunnelsButton";
Il faudrait peut être voir pour renommer ce composant qui contient au final un bouton valider et annuler. Cela simplifierai le code pour son intégration.

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/VariablesResume.tsx
> +const localStyle = StyleSheet.create({
Ce style peut être standardisé car il est partagé avec Sequence.tsx et SequenceItem.tsx

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/VariableItem.tsx
> +const localStyle = StyleSheet.create({
Ce style peut être standardisé car il est partagé avec Sequence.tsx et SequenceItem.tsx

2024-03-18 13:17 UTC, Guillaume35 commented on components/Session/VariablesResume.tsx
ce composant peut être standardisé : il est partagé avec Sequence.tsx et SequenceItem.tsx

2024-03-18 13:17 UTC, Guillaume35 commented on components/TunnelsButton.tsx
> +        width: "47%",
ne pas utiliser de largeur fixée, utiliser des flexbox

2024-03-18 13:17 UTC, Guillaume35 commented on components/TunnelsButton.tsx
> +        backgroundColor: '#00000000',
utiliser les variables de couleur disponible dans global style à la place.

2024-03-18 13:17 UTC, Guillaume35 commented on components/TunnelsButton.tsx
> +        marginBottom: 20
utiliser un style de global style à la place : mb2Container par exemple.

2024-03-18 13:17 UTC, Guillaume35 commented on components/TunnelsButton.tsx
> +        fontSize: 16,
Pas d'utilisation de valeur arbitraire, utiliser une variable de global style pour la fontSize.

2024-03-18 13:17 UTC, Guillaume35 commented on components/TunnelsButton.tsx
> +        marginBottom: 5,
utiliser une variable de global style pour le marginContent.

2024-03-18 14:57 UTC, marilehoux commented on app/(tabs)/session/validate.tsx
> +            <Text style={globalStyles.textLight}>{currentSession.start.toLocaleDateString()}</Text>
done

2024-03-18 15:26 UTC, marilehoux commented on app/(tabs)/session/validate.tsx
> +            <Title title={"Pointages"} style={[globalStyles.mb2Container, globalStyles.textLight]} />
ok

2024-03-18 15:26 UTC, marilehoux commented on app/(tabs)/session/validate.tsx
> +            <StopWatch
ok

2024-03-18 15:30 UTC, marilehoux commented on app/(tabs)/session/validate.tsx
> +            <View style={globalStyles.mt2Container}>
ok

2024-03-18 15:43 UTC, marilehoux commented on app/(tabs)/session/validate.tsx
> +    containerLocal: {
ok

2024-03-19 09:23 UTC, marilehoux commented on app/(tabs)/session/validate.tsx
> +            <Title title={"Informations fournies"} style={[globalStyles.mb2Container, globalStyles.textLight]} />
a re préciser y?

2024-03-19 09:24 UTC, marilehoux commented on components/Form/DateTimeInput.tsx
en cours

2024-03-19 09:25 UTC, marilehoux commented on components/Onboarding/OnboardingController.tsx
> +import VariablesResume from "../Session/VariablesResume";
ok

2024-03-19 09:38 UTC, marilehoux commented on components/Session/SequenceItem.tsx
> +    const [updatedItem0, setUpdatedItem0] = React.useState<Date>(item[0]);
ok. reste onchange à mettre en place

2024-03-19 09:38 UTC, marilehoux commented on components/Session/SequenceItem.tsx
> +    , [updatedItem0])
ok

2024-03-19 09:42 UTC, marilehoux commented on components/Session/SequenceItem.tsx
> +                    <View style={localStyle.small}>
ok ios à vérif sur android

2024-03-19 09:42 UTC, marilehoux commented on components/Session/SequenceItem.tsx
> +    const handleChangeValue = (newVal: Date) => {
ok

2024-03-19 09:42 UTC, marilehoux commented on components/Session/SequenceItem.tsx
> +                            placeholder={item[0].toLocaleTimeString()}
ok

2024-03-19 09:45 UTC, marilehoux commented on components/Session/SequenceItem.tsx
> +    small: {
ok

2024-03-19 09:46 UTC, marilehoux commented on components/Session/SequenceList.tsx
> +import Title from "../Title";
ok

2024-03-19 09:46 UTC, marilehoux commented on components/Session/SequenceList.tsx
> +import { globalStyles } from "../../shared/globalStyles";
OK

2024-03-19 09:49 UTC, marilehoux commented on components/Session/VariableItem.tsx
> +    const [isEditable, setIsEditable] = React.useState(false)
ok

2024-03-19 09:53 UTC, marilehoux commented on components/Session/VariableItem.tsx
> +                        <ButtonPrevNext
Ok

2024-03-19 10:02 UTC, marilehoux commented on components/Session/VariableItem.tsx
> +import ButtonPrevNext from "../TunnelsButton";
ok

2024-03-19 10:07 UTC, marilehoux commented on components/TunnelsButton.tsx
> +        backgroundColor: '#00000000',
ok

2024-03-19 10:08 UTC, marilehoux commented on components/TunnelsButton.tsx
> +        marginBottom: 20
ok

2024-03-19 10:10 UTC, marilehoux commented on components/TunnelsButton.tsx
> +        fontSize: 16,
ok

2024-03-19 10:44 UTC, marilehoux commented on components/TunnelsButton.tsx
> +        marginBottom: 5,
ok

2024-03-19 10:46 UTC, marilehoux commented on components/Session/SequenceItem.tsx
> +    const [isEditable, setIsEditable] = React.useState(false);
ok

2024-03-19 10:47 UTC, marilehoux commented on components/Session/SequenceItem.tsx
> +                    <View style={localStyle.small}>
ok vérif ios

2024-03-19 13:11 UTC, marilehoux commented on components/Form/TextInputC.tsx
ok

2024-03-19 13:12 UTC, marilehoux commented on components/Form/TextInputC.tsx
> -import { TextInput as ReactTextInput } from 'react-native';
ok

2024-03-19 13:13 UTC, marilehoux commented on components/Form/FormInput.tsx
> +import TextInputC from "./TextInputC";
ok

2024-03-19 13:14 UTC, marilehoux commented on components/Form/TextInputC.tsx
> +import { TextInput } from "react-native";
ok

2024-03-19 13:14 UTC, marilehoux commented on components/Form/TextInputC.tsx
> +const TextInputC = ({value, onChange, placeholder, multiline}: TextInputOptions) => {
ok

2024-03-19 13:14 UTC, marilehoux commented on components/Form/TextInputC.tsx
> +export default TextInputC;
ok

2024-03-19 13:15 UTC, marilehoux commented on components/Form/TextInputC.tsx
> +        <TextInput
ok

2024-03-19 13:15 UTC, marilehoux commented on components/Form/TextInputC.tsx
> +const TextInputC = ({value, onChange, placeholder, multiline}: TextInputOptions) => {
ok

2024-03-19 13:16 UTC, marilehoux commented on components/Form/TextInputC.tsx
> -import { TextInput as ReactTextInput } from 'react-native';
as ReactNativeTextInput

2024-03-19 13:16 UTC, marilehoux commented on components/Form/TextInputC.tsx
> -import { TextInput as ReactTextInput } from 'react-native';
ok

2024-03-19 13:54 UTC, marilehoux commented on components/Session/VariableItem.tsx
> +const localStyle = StyleSheet.create({
ok

2024-03-19 14:27 UTC, marilehoux commented on components/Session/VariablesResume.tsx
> +const localStyle = StyleSheet.create({
ok

2024-03-19 14:37 UTC, marilehoux commented on components/Session/VariablesResume.tsx
ok

2024-03-19 14:46 UTC, marilehoux commented on app/(tabs)/session/validate.tsx
> +            <Title title={"Informations fournies"} style={[globalStyles.mb2Container, globalStyles.textLight]} />
ok

2024-03-19 14:47 UTC, marilehoux commented on components/Form/TextInputC.tsx
> +const TextInputC = ({value, onChange, placeholder, multiline}: TextInputOptions) => {
a revoir fonctionnement text input dans le tunnel

2024-03-19 17:00 UTC, marilehoux commented on components/Form/DateTimeInput.tsx
ok pour date et time, reste datetime

2024-03-20 08:52 UTC, marilehoux commented on components/Form/DateTimeInput.tsx
date time ok

2024-03-20 09:42 UTC, marilehoux commented on components/Form/TextInputC.tsx
> +const TextInputC = ({value, onChange, placeholder, multiline}: TextInputOptions) => {
ok

2024-03-20 14:27 UTC, marilehoux commented on components/Session/VariableItem.tsx
> +    }, [variable.value])
ok use effect commenter. cela n'altere pas la modification sur la derniere page.

2024-03-20 15:24 UTC, marilehoux commented
Il reste un bug sur android dans la progression de Onboard controller . Je ne comprends pas pourquoi.
Les changements ne sont pas pris en compte dans raxvariables et raw datas

2024-03-22 15:05 UTC, merged